## The DNS provider where the DNS records will be created
provider: aws

# AWS Access keys to inject as environment variables
aws:
  secretKey: ""
  accessKey: ""
  # pre external-dns 0.5.9 home dir should be `/root/.aws`
  credentialsPath: "/.aws"
  roleArn: ""
  region: ${aws_default_region}
  # Filter for zones of this type (optional, options: public, private)
  zoneType: ""