apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ${letsencrypt_env}
spec:
  acme:
    server: ${letsencrypt_endpoint}
    email: ${letsencrypt_issuer_email}
    privateKeySecretRef:
      name: ${letsencrypt_env}
    http01: {}
